const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
let lastPage;
(async()=>{
 const fixture=JSON.parse(fs.readFileSync(process.env.TNCP_REVIEW_FIXTURE,'utf8'));
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1600,height:1100}});lastPage=page;page.setDefaultTimeout(20000);
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:8765/wp-login.php');await page.evaluate(password=>{document.getElementById('user_login').value='tncp_admin';document.getElementById('user_pass').value=password;},process.env.TNCP_TEST_PASSWORD);await page.locator('#wp-submit').click();await page.waitForURL('**/wp-admin/');
 await page.goto('http://127.0.0.1:8765/wp-admin/admin.php?page=tn-content-planner');await page.getByRole('tab',{name:/^Pages,/}).click();
 async function checkCounts(){await page.waitForFunction(()=>document.getElementById('tncp-app').getAttribute('aria-busy')==='false');const current=await page.evaluate(async()=>await(await fetch(TNCP.api+'plan/page',{headers:{'X-WP-Nonce':TNCP.nonce}})).json());const mapped=current.plan.rows.filter(r=>current.catalog.some(p=>p.id===r.post_id)).length;await page.getByRole('tab',{name:`Pages, ${mapped} of ${current.plan.rows.length} mapped`,exact:true}).waitFor();}
 await checkCounts();
 assert.equal(await page.locator('tbody td:nth-child(4) a').count(),0);
 assert.equal(await page.getByRole('button',{name:'1. Plan your WBS',exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'2. Review & create',exact:true}).count(),0);
 const selectAll=page.getByRole('checkbox',{name:'Select all rows',exact:true});
 await selectAll.check();await selectAll.uncheck();
 if(await page.locator('tbody td:first-child input:checked').count())throw Error('Header did not clear selection');
 await page.locator('tbody tr').first().getByRole('checkbox').first().check();
 if(!await selectAll.evaluate(node=>node.indeterminate))throw Error('Header missing partial state');
 await selectAll.check();await selectAll.uncheck();
 for(const id of ['review-one','review-two','review-three'])await page.locator(`[data-row="${id}"] td:first-child input`).check();
 await page.getByRole('button',{name:'Review & create selected',exact:true}).click();
 await page.getByText('Item 1 of 3',{exact:true}).waitFor();
 const matches=page.locator('.tncp-match');
 assert.match(await matches.nth(0).innerText(),/Exact slug/);
 assert.match(await matches.nth(1).innerText(),/Exact title/);
 assert.match(await matches.nth(2).innerText(),/2 words matched/);
 assert.match(await matches.nth(3).innerText(),/1 word matched/);
 assert.equal(await page.getByRole('button',{name:'Apply & next',exact:true}).isDisabled(),true);
 await matches.nth(1).click();await page.getByRole('radio',{name:/^Accept destination/}).check();
 fs.mkdirSync('tests/artifacts',{recursive:true});
 await page.screenshot({path:'tests/artifacts/reconcile-desktop.png',fullPage:true});
 if(process.env.TNCP_AXE_PATH){
  await page.addScriptTag({path:process.env.TNCP_AXE_PATH});
  for(const viewport of [{width:1600,height:1100},{width:390,height:844}]){
   await page.setViewportSize(viewport);
   const audit=await page.evaluate(async()=>await axe.run('.tncp-wrap',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));
   assert.deepEqual(audit.violations.map(item=>item.id),[]);
  }
  await page.screenshot({path:'tests/artifacts/reconcile-mobile.png',fullPage:true});await page.setViewportSize({width:1600,height:1100});
 }
 await page.getByRole('button',{name:'Apply & next',exact:true}).click();await page.getByText('Item 2 of 3',{exact:true}).waitFor();
 await page.getByRole('radio',{name:/^Create new/}).check();
 assert.equal(await page.getByRole('combobox',{name:'New post status',exact:true}).inputValue(),'publish');
 await page.getByRole('combobox',{name:'New post status',exact:true}).selectOption('draft');
 await page.getByRole('textbox',{name:'New post slug',exact:true}).fill(fixture.prefix+'-plan');
 await page.getByRole('button',{name:'Apply & next',exact:true}).click();await page.getByText('That slug already exists.',{exact:false}).waitFor();
 assert.equal(await page.getByText('Item 2 of 3',{exact:true}).count(),1);
 await page.getByRole('textbox',{name:'New post slug',exact:true}).fill(fixture.prefix+'-new');
 await page.getByRole('button',{name:'Apply & next',exact:true}).click();await page.getByText('Item 3 of 3',{exact:true}).waitFor();
 await checkCounts();
 await page.locator('.tncp-match').filter({hasText:'Legacy Article'}).click();await page.getByRole('radio',{name:/^Accept source/}).check();
 await page.getByRole('button',{name:'Apply & finish',exact:true}).click();await page.getByRole('heading',{name:'Review complete',exact:true}).waitFor();
 await checkCounts();
 const data=await page.evaluate(async()=>await (await fetch(TNCP.api+'plan/page',{headers:{'X-WP-Nonce':TNCP.nonce}})).json());
 assert.equal(data.plan.rows[0].post_id,fixture.posts[1]);
 assert.equal(data.plan.rows[0].slug,fixture.prefix+'-exact-title');
 assert.equal(data.plan.rows[2].post_id,fixture.posts[4]);
 const posts=await page.evaluate(async ids=>Promise.all(ids.map(async id=>(await (await fetch(`/index.php?rest_route=/wp/v2/pages/${id}&context=edit`,{headers:{'X-WP-Nonce':TNCP.nonce}})).json()))),[fixture.posts[0],data.plan.rows[1].post_id,fixture.posts[4]]);
 assert.equal(posts[0].title.raw,'Garden Planning');assert.equal(posts[1].status,'draft');assert.equal(posts[2].title.raw,'Legacy Redesign');assert.equal(posts[2].content.raw,'Keep existing content');
 await page.getByRole('button',{name:'Back to plan',exact:true}).click();
 const mappedDots=page.locator('[data-row="review-three"] .tncp-post-indicators');
 assert.equal(await mappedDots.getAttribute('aria-label'),'Has content; No featured image');
 assert.equal(await mappedDots.locator('.is-present').count(),1);
 assert.deepEqual(await mappedDots.locator('.tncp-post-dot').evaluateAll(nodes=>nodes.map(node=>getComputedStyle(node).visibility)),['visible','hidden']);
 const emptyDots=page.locator('tbody tr').filter({has:page.getByRole('button',{name:'Edit title: Entirely New Article',exact:true})}).locator('.tncp-post-dot');
 assert.deepEqual(await emptyDots.evaluateAll(nodes=>nodes.map(node=>getComputedStyle(node).visibility)),['hidden','hidden']);
 await page.locator('.tncp-scroll').evaluate(node=>{node.scrollLeft=node.scrollWidth});
 await page.screenshot({path:'tests/artifacts/post-indicators.png',fullPage:true});
 // Skip leaves the current item selected and unchanged.
 await page.getByRole('button',{name:'Add row',exact:true}).click();const row=page.locator('tbody tr').last();
 await row.getByRole('textbox',{name:'Title, HTML allowed',exact:true}).fill('Skip this item');await row.getByRole('textbox',{name:'Title, HTML allowed',exact:true}).press('Tab');
 await row.getByRole('textbox',{name:'Content slug',exact:true}).fill(fixture.prefix+'-skip');await row.getByRole('textbox',{name:'Content slug',exact:true}).press('Tab');
 await page.getByRole('button',{name:'Save plan',exact:true}).click();await page.getByText('Plan saved.',{exact:false}).waitFor();
 await checkCounts();
 await row.getByRole('checkbox',{name:'Select Skip this item',exact:true}).check();await page.getByRole('button',{name:'Review & create selected',exact:true}).click();
 await page.getByText('Item 1 of 1',{exact:true}).waitFor();await page.getByRole('button',{name:'Skip for now',exact:true}).click();
 await page.getByText('0 applied · 1 skipped.',{exact:false}).waitFor();await page.getByRole('button',{name:'Back to plan',exact:true}).click();
 assert.equal(await row.getByRole('checkbox',{name:'Select Skip this item',exact:true}).isChecked(),true);
 await row.getByRole('button',{name:'Remove row: Skip this item',exact:true}).click();await page.getByRole('button',{name:'Remove row',exact:true}).click();
 // Tab click reloads linked data and exposes an Ajax loading state.
 await page.getByRole('button',{name:'Save plan',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('tncp-app').getAttribute('aria-busy')==='false');
 assert.equal(await page.getByRole('button',{name:'Refresh linked posts',exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Select all',exact:true}).count(),0);
 let releaseRefresh;const refreshGate=new Promise(resolve=>releaseRefresh=resolve);
 await page.route('**/*refresh/page',async route=>{await refreshGate;await route.continue();});
 const beforeBox=await page.locator('#tncp-panel').evaluate(node=>({top:node.getBoundingClientRect().top+scrollY,height:node.getBoundingClientRect().height}));
 const refreshRequest=page.waitForRequest(request=>request.url().includes('refresh/page'));
 await page.getByRole('tab',{name:/^Pages,/}).click();await refreshRequest;
 assert.equal(await page.locator('#tncp-loading').isVisible(),true);
 assert.deepEqual(await page.locator('#tncp-panel').evaluate(node=>({top:node.getBoundingClientRect().top+scrollY,height:node.getBoundingClientRect().height})),beforeBox);
 assert.equal(await page.locator('#tncp-loading').evaluate(node=>getComputedStyle(node).position),'fixed');
 releaseRefresh();await page.waitForFunction(()=>document.getElementById('tncp-loading').hidden);
 await page.unroute('**/*refresh/page');
 assert.equal(await page.getByRole('tab',{name:/^Pages,/}).evaluate(node=>getComputedStyle(node).top),'1px');
 // Linked rows offer a separate, recoverable bin action.
 await page.locator('[data-row="review-three"]').getByRole('button',{name:/^Remove row:/}).click();
 await page.getByRole('button',{name:'Remove row only',exact:true}).waitFor();
 await page.screenshot({path:'tests/artifacts/bin-modal.png',fullPage:true});
 await page.getByRole('button',{name:'Remove row & move post to bin',exact:true}).click();
 await checkCounts();
 const binned=await page.evaluate(async id=>(await (await fetch(`/index.php?rest_route=/wp/v2/pages/${id}&context=edit`,{headers:{'X-WP-Nonce':TNCP.nonce}})).json()),fixture.posts[4]);
 assert.equal(binned.status,'trash');
 await page.screenshot({path:'tests/artifacts/planner-desktop.png',fullPage:true});
 // CSV contract still has exactly two columns.
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Download CSV template',exact:true}).click();const download=await downloading;
 assert.equal(fs.readFileSync(await download.path(),'utf8').replace(/^\uFEFF/,''),'title,slug\r\n');
 // Pattern totals and editable metadata, with editor links.
 const contentLink=page.locator('tbody a[target="_blank"]').first();
 assert.match(await contentLink.getAttribute('href'),/post\.php\?post=\d+&action=edit/);
 const xp=page.getByRole('tab',{name:'XP Patterns',exact:true});
 assert.equal(await page.getByRole('tab').last().innerText(),'XP Patterns');await xp.click();
 await page.getByRole('button',{name:'Save patterns',exact:true}).waitFor();
 const patternRow=page.locator('[data-pattern]').first();
 await patternRow.getByRole('textbox').fill('Reusable content layout');
 await patternRow.getByRole('combobox',{name:/^Status/}).selectOption('in-progress');
 const example=patternRow.getByRole('combobox',{name:/^Example post/});
 const exampleId=await example.locator('option').nth(1).getAttribute('value');await example.selectOption(exampleId);
 const editorLink=patternRow.locator('a');assert.equal(await editorLink.getAttribute('target'),'_blank');
 assert.match(await editorLink.getAttribute('href'),new RegExp('post='+exampleId+'&action=edit'));
 await page.getByRole('button',{name:'Save patterns',exact:true}).click();await page.getByText('Patterns saved.',{exact:true}).waitFor();
 await xp.click();await page.waitForFunction(()=>document.getElementById('tncp-app').getAttribute('aria-busy')==='false');
 assert.equal(await patternRow.getByRole('textbox').inputValue(),'Reusable content layout');
 assert.equal(await patternRow.getByRole('combobox',{name:/^Status/}).inputValue(),'in-progress');
 assert.equal(await patternRow.getByRole('combobox',{name:/^Example post/}).inputValue(),exampleId);
 await page.screenshot({path:'tests/artifacts/patterns-desktop.png',fullPage:true});
 if(process.env.TNCP_AXE_PATH){for(const viewport of [{width:1600,height:1100},{width:390,height:844}]){await page.setViewportSize(viewport);const audit=await page.evaluate(async()=>await axe.run('.tncp-wrap',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.deepEqual(audit.violations.map(item=>item.id),[]);}}
 assert.deepEqual(errors,[]);console.log('PASS: ordered matches, all three reconciliation choices, one-item advancement, failure retry, skip, live tab counts, CSV and accessibility.');
 await browser.close();
})().catch(async error=>{console.error(error);if(lastPage){console.error(await lastPage.locator('#tncp-notice').innerText().catch(()=>''));await lastPage.screenshot({path:'tests/artifacts/reconcile-failure.png',fullPage:true}).catch(()=>{});}process.exit(1)});
